before_build:
  - nuget restore
platform: x64
configuration:
  - Debug
  - Release
build:
  parallel: true
  project: src/Backuper.sln
  verbosity: normal
before_build:
  - cmd: >-
    cd src
    nuget restore